name: Semantic tests

on: workflow_dispatch

env:
  CAIRO_LANG_VERSION: 0.10.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9 # Cairo was tested with this version

      - name: Install dependencies
        run: |
          yarn
          pipx install black[colors]
          pip install cairo-lang=="$CAIRO_LANG_VERSION"

      - name: Build warplib
        run: yarn warplib

      - name: Check formatting
        run: |
          yarn lint
          black starknet-testnet/ --check --verbose --diff --color
          find warplib/ -iname *.cairo -exec cairo-format -c {} +

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Setup gcc-11 Environment
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install -y gcc-11 gcc-11-multilib g++-11 g++-11-multilib
          gcc-11 --version

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9 # Cairo was tested with this version

      - name: Install dependencies
        run: |
          make
          make compile

      - name: Setup warp_venv
        run: bin/warp install --python python --verbose

      - name: Build warplib
        run: yarn warplib

      - name: Test code execution
        run: |
          yarn testnet:benchmark &
          node build/autoRunSemanticTests.js
